language: python
python:
  - "3.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - sh miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  
  - conda create -q -n test-environment python=3.7 bcbio-gff pyvcf bcftools
  - conda activate test-environment

script:
  python test/parse_vcf.test.py
