jobs: 100
cluster: 
    mkdir -p results/{config[batch]}/slurm_logs/{rule}/ &&
    sbatch
    --partition={resources.partition}
    --cpus-per-task={resources.cpus}
    --job-name={rule}-{wildcards}
    --output=results/{config[batch]}/slurm_logs/{rule}/{rule}-{wildcards}-%j.out
    --mail-type=FAIL
    --mail-user=timothy.j.thurman@gmail.com
default-resources: 
  - cpus=1
  - partition="good_lab_reincarnation"
latency-wait: 15
verbose: true
quiet: true
